### ISSUE TITLE
Command doesn't work

### ISSUE THREAD

**Issue by Marta83** [bubnovKelnik/tenserflow-bundle#1]
If I execute the command the output is : Done! , but no labels appear. 

In addition to the basic installation do I have to configure something else to work?

Thank u so much in advance

**Comment by bubnov-mikhail** [comment]
There are 3 commands in this bundle :)
Which one do you mean?

If you run commands to create dictionary without optional args, check /tmp directory.

**Comment by bubnov-mikhail** [comment]
As it is said in README, command uses GNU parallel.

**Comment by Marta83** [comment]
Hi!

Sorry, I'm talking abour this command:  bubnov_tensorflow:recognize /absolute/path/to/image.ext

**Comment by bubnov-mikhail** [comment]
Have you installed this bundle with composer? Did you add 
"scripts": {
        "post-install-cmd": [ "TensorFlowBinaryInstaller::install" ],
        "post-update-cmd":  [ "TensorFlowBinaryInstaller::update" ]
 },

in composer.json to download and install tenservlow binary?

**Comment by bubnov-mikhail** [comment]
Could you attach the image?
